
import java.awt.Toolkit;
import javax.swing.*;
import java.awt.* ; 
import java.awt.event.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marwan
 */
public class Maze extends javax.swing.JFrame {

    /**
     * Creates new form maze
     */
    public Maze() {
        initComponents();
    }
    
    
     
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        africaframe = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        button1 = new java.awt.Button();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        africaframe.setFont(new java.awt.Font("Adobe Arabic", 1, 10)); // NOI18N
        africaframe.setName("africaframe"); // NOI18N
        africaframe.setSize(new java.awt.Dimension(890, 550));
        africaframe.getContentPane().setLayout(null);

        jTextPane1.setEditable(false);
        jTextPane1.setText("1) The name ‘Africa’ came into Western use through the Romans. The word has its roots in two different languages – in Latin (“Aprica”) it means ‘Sunny’, and in Greek (“Aphrike”) it means ‘Without cold’.\n\n2) The oldest human remains ever discovered were found in Ethiopia, which is approximately 200,000-year-old.\n\n3) Between the period of 1881 and 1914, entire African continent went through the turmoil of invasion, occupation, division, colonization and annexation by European powers. This phase was popularly known as “Scramble of Africa”. Only Ethiopia and Liberia were out of this turmoil.\n\n4) The Second Congo War (1998-2006), claimed the second-highest number of casualties (5.4 million lives) since World War II. The conflict involved eight African countries.\n\n5) Between 1525 and 1866, 12.5 million Africans were kidnaped and sold into slavery in the Americas.\n\n6) Africa has the world’s longest river, the Nile (4,132 miles). The Nile runs through 11 countries in Africa.\n\n7)Africa also has the world’s largest desert, Sahara, which is nearly as big as the USA!\n\n8) Not just that, but the largest waterfalls, the Victoria falls is also in Africa. Victoria Falls is one of the 7 natural wonders of the world.");
        jTextPane1.setAutoscrolls(false);
        jTextPane1.setPreferredSize(new java.awt.Dimension(915, 510));
        jScrollPane1.setViewportView(jTextPane1);

        africaframe.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 870, 310);

        jLabel9.setText("1- How many countries does the longest river in Africa run through ? ");
        africaframe.getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 320, 390, 30);

        jLabel10.setText("2- What is the name of the world's largest desert ? ");
        africaframe.getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 370, 380, 30);

        jLabel11.setText("3- How many african countries were involved in the Second Congo War ?");
        africaframe.getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 430, 430, 30);

        buttonGroup2.add(r1);
        r1.setText("Mojave");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        africaframe.getContentPane().add(r1);
        r1.setBounds(20, 400, 80, 30);

        buttonGroup2.add(r2);
        r2.setText("Sahara");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        africaframe.getContentPane().add(r2);
        r2.setBounds(150, 400, 80, 30);

        buttonGroup2.add(r3);
        r3.setText("Kalahari");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });
        africaframe.getContentPane().add(r3);
        r3.setBounds(280, 400, 80, 30);

        buttonGroup2.add(r4);
        r4.setText("Gibson");
        africaframe.getContentPane().add(r4);
        r4.setBounds(410, 400, 70, 30);

        buttonGroup1.add(r5);
        r5.setText("8");
        africaframe.getContentPane().add(r5);
        r5.setBounds(20, 350, 31, 30);

        buttonGroup1.add(r6);
        r6.setText("9");
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        africaframe.getContentPane().add(r6);
        r6.setBounds(150, 350, 31, 30);

        buttonGroup1.add(r7);
        r7.setText("10");
        africaframe.getContentPane().add(r7);
        r7.setBounds(280, 350, 37, 30);

        buttonGroup1.add(r8);
        r8.setText("11");
        africaframe.getContentPane().add(r8);
        r8.setBounds(410, 350, 37, 30);

        buttonGroup3.add(r9);
        r9.setText("7");
        r9.setName("ans3"); // NOI18N
        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });
        africaframe.getContentPane().add(r9);
        r9.setBounds(20, 470, 31, 23);

        buttonGroup3.add(r10);
        r10.setText("5");
        r10.setName("ans3"); // NOI18N
        africaframe.getContentPane().add(r10);
        r10.setBounds(150, 470, 31, 23);

        buttonGroup3.add(r11);
        r11.setText("8");
        r11.setName("ans3"); // NOI18N
        africaframe.getContentPane().add(r11);
        r11.setBounds(280, 470, 31, 23);

        buttonGroup3.add(r12);
        r12.setText("10");
        r12.setName("ans3"); // NOI18N
        africaframe.getContentPane().add(r12);
        r12.setBounds(410, 470, 37, 23);

        button1.setBackground(new java.awt.Color(51, 0, 255));
        button1.setFont(new java.awt.Font("DotumChe", 1, 12)); // NOI18N
        button1.setLabel("Score");
        button1.setName("calc_score"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        africaframe.getContentPane().add(button1);
        button1.setBounds(740, 464, 90, 40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maze");
        setName("mainframe"); // NOI18N
        setPreferredSize(new java.awt.Dimension(890, 510));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setText("NORTH AMERICA");
        jLabel2.setName("NA"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 80, 100, 50);

        jLabel3.setText("AFRICA");
        jLabel3.setName("AFRICA"); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 150, 90, 50);

        jLabel4.setText("SOUTH AMERICA");
        jLabel4.setToolTipText("South America");
        jLabel4.setName("SA"); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 240, 90, 50);

        jLabel5.setText("   EUROPE");
        jLabel5.setName("EU"); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 80, 60, 20);

        jLabel6.setText("                          ASIA");
        jLabel6.setName("ASIA"); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 60, 170, 70);

        jLabel7.setText("AUSTRALIA");
        jLabel7.setName("AUST"); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(700, 290, 90, 30);

        jLabel8.setText("                                                                       ANTARCTICA");
        jLabel8.setName("ANTR"); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 440, 490, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marwan\\Desktop\\ct.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(900, 495));
        jLabel1.setMinimumSize(new java.awt.Dimension(900, 495));
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 495);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
        
    
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"North America"); 
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        africaframe.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"South America");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Europe");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Asia");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Australia");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Antarctica");
    }//GEN-LAST:event_jLabel8MouseClicked

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r9ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r3ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        // TODO add your handling code here:
         String answer1 = "Answer num. 2 is wrong \n" , answer2 = "Answer num. 1 is wrong \n" , answer3 = "Answer num. 3 is wrong \n";
         int score = 0;
   
            if(r2.isSelected()){
                score += 1;
                answer1= "Answer num. 2 is right \n";
                               }
            if(r8.isSelected()){
                score += 1;
                answer2= "Answer num. 1 is right \n";
                               }
            if(r11.isSelected()){
                score += 1;
                answer3= "Answer num. 3 is right \n";
                               }
            
            JOptionPane.showMessageDialog(this, answer2 + answer1 + answer3 + "----------------------------------------\n "+""
                    + "Your score is " + score + " / 3");
       
    }//GEN-LAST:event_button1ActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel1FocusGained

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        this.jLabel2.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        this.jLabel3.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        this.jLabel4.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        this.jLabel5.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        this.jLabel6.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        this.jLabel7.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        this.jLabel8.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
         this.jLabel2.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel2MouseExited
     
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Maze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Maze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Maze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Maze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Maze().setVisible(true);
              
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame africaframe;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables

  

}
